### ISSUE TITLE
Error creating jds instance

### ISSUE THREAD

**Issue by bciv** [KRMAssociatesInc/eHMP#15]
Received 'No such file or directory' when running:

Step iv
sudo ./createJDSinstance.sh -i jds

This problem was resolved by running the following command prior to creating the instance:

dos2unix createJDSinstance.sh 

Please add this step in your documentation prior to creating the JDS instance.

**Comment by SarahRatzlaff** [comment]
Thank you so much!! This was where I was stuck !
Sarah Ratzlaff

**Comment by khollida** [comment]
Can you provide more details on your environment, specifically OS?

**Comment by bciv** [comment]
I am running the build from a Windows 10 box but the environment where the error occurs is from within the Ubuntu box referenced by the Vagrantfile located in the root of the eHMP repository.
